### ISSUE TITLE
Limit free responses to 10,000 characters

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-server#1000]
Because... Moby Dick

/cc @heathersee

**Comment by philschatz** [comment]
There should maybe also be a FE PR for this (I guess it's optional though) /cc @openstax/tutor-fe

**Comment by philschatz** [comment]
# :tada: :balloon: :sparkles: #1000 !!!! :sparkles: :balloon: :tada:

**Comment by Dantemss** [comment]
This is necessary because exceeding Excel's limit of 32,767 characters breaks the research export (in Excel).
