### ISSUE TITLE
GenericAssistant allows different fields to be updated compared to TaskPlan model

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-server#1054]
After tasks are open. Figure out which fields should be modifiable...

**Comment by jpslav** [comment]
Also, the assistant is ignoring model validations by [using `update_all`](https://github.com/openstax/tutor-server/blob/master/app/routines/propagate_task_plan_updates.rb#L16)

**Comment by Dantemss** [comment]
`update_all` was most likely a performance fix (task_plan updates taking several minutes).

**Comment by Dantemss** [comment]
It seems to me that the updatable attributes should just be moved into the TaskPlan model so we remember to keep them in sync.

**Comment by nathanstitt** [comment]
Yeah, maybe... I don't care terribly much either way, but the logical conclusion to that argument is that all the assistant's logic should move there. .. just sayin' 😁

**Comment by nathanstitt** [comment]
actually not all I guess.  The reason we had the update happening in the assistant is so we could have different implementation for homework's `opens_at`.  I guess the rule could be "common logic" goes into task-plan

**Comment by Dantemss** [comment]
Maybe this can wait until we allow teachers to set feedback dates freely, then it won't matter and we can move the method into the TaskPlan.

**Comment by Dantemss** [comment]
This has been done.
