### ISSUE TITLE
Change all `timezone`s to `time_zone`

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#1084]
Right now we use a mix of both, but Rails treats them as separate words (e.g. `ActiveSupport::TimeZone`) so we might as well make that the standard.  The course profile JSON will either need to keep a deprecated `timezone` property or we'll have to update the FE too.

**Comment by Dantemss** [comment]
I believe this has been done in https://github.com/openstax/tutor-server/pull/1077

**Comment by Dantemss** [comment]
We updated all timezone to time_zone in the BE and FE.
