### ISSUE TITLE
Replace implementation of GetBookToc with VisitBook

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#125]
`Content::Api::VisitBook` is a new routine for traversing a book structure and reporting back information.  I wrote it to get exercise and tag information out of a book, but to test it at first I wrote a visitor to compute the table of contents like how we do in `GetBookToc`.  

To simplify code, replace `GetBookToc` with this new `VisitBook` routine.

**Comment by Dantemss** [comment]
Thought you hated visitors :D

**Comment by Dantemss** [comment]
All done.
