### ISSUE TITLE
Avoid validations during lazy load of url and title in TaskedExercise

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#164]
A `TaskedExercise`'s `url` and `title` are lazily persisted in a way that conflicts with the fact that these models aren't to be updated after they are completed.  This results in continual save failures over and over, evidenced by `begin transaction` `rollback transaction` pairs in the logs. 

Instead of 

```ruby
def url
  u = super
  return u unless u.nil?
  u = wrapper.url
  self.url = u
  save if persisted?
  u
end
```

do something like

```ruby
def url
  u = super # could also say u = read_attribute(:url)
  return u unless u.nil?
  u = wrapper.url
  self.update_attribute(:url, u) if persisted? # skips validations
  u
end
```

or you could eliminate the repeated code with

```ruby
def url
  get_or_lazily_store(:url)
end

def title
  get_or_lazily_store(:title)
end

def get_or_lazily_store(attribute_name)
  value = read_attribute(attribute_name)
  return value if value.present?

  value = wrapper.send(attribute_name)
  self.update_attribute(attribute_name, value) if persisted?
  value
end
```

**Comment by Dantemss** [comment]
I know I was responsible for those models, but I think maybe we should just remove the laziness here... I made a Domain::TaskExercise routine to create them that should set everything properly anyway...

**Comment by jpslav** [comment]
@kevinburleigh75 was of the same mind.

**Comment by Dantemss** [comment]
This one seems done. PR is merged.
