### ISSUE TITLE
Bug - Highlight icons not appearing for certain text/math/images in chrome, firefox, edge

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor-server#1792]
Bug - Highlight icons not appearing for certain text/math/images. Noticed in chrome, firefox & safari
[edge.JPG](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/b8fafd28-39c8-4883-9d2c-5d6a3ef52d48)

**Comment by Malar-Natarajan** [comment]
![Screen Shot 2018-10-04 at 1.43.16 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/4b02f627-66fd-4db5-a09b-d77f27231d30)

**Comment by Malar-Natarajan** [comment]
The highlight icon did display for the same content in safari. But I had issues with chrome & edge on specific content,. Refer this comparative screenshot![Screen Shot 2018-10-04 at 2.11.00 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/cf7ba333-b3c8-4dd1-90b5-f87b321663a0)

**Comment by BruceP99166** [comment]
Issue moved to [openstax/tutor #78](https://github.com/openstax/tutor/issues/78) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mhapich** [comment]
That is happening to me too.  It happens in different OpenStax books in some sections.  Is there a solution to this problem yet?  I have to work on a Dell at work, so the Safari fix won't help.

**Comment by nathanstitt** [comment]
@mhapich Thanks for letting us know you're having this as well.   We thought we'd fixed this but it sounds like it's still occurring.   Can you provide a few links to where you see it happening?   Thanks so much!

**Comment by kjdav** [comment]
@mhapich good afternoon! I sent you a follow up via email (using the email in your GH profile). I'd like to close this GH issue and discuss over email so we can get more details from you. thanks.
