### ISSUE TITLE
Sync with Accounts broken

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-server#1797]
A new adjunct role was added to Accounts but it was not added to accounts-rails.

**Comment by Malar-Natarajan** [comment]
tutor syncing with accounts is broken... a new adjunct role was added to accounts but was not added to https://github.com/openstax/accounts-rails (edited)

Profile updates in accounts will not show up in Tutor until this is fixed.

main issue is if you set anyone in accounts-qa as the adjunct role, then update someone else's name in their profile, Tutor will never see the changes (but it also interferes with syncing with salesforce)

**Comment by Malar-Natarajan** [comment]
Verified in QA
