### ISSUE TITLE
Use environment specific links

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor-server#1827]
Currently the errata form links to production even if it's on DEV, QA or staging.  This causes testers create "real" bug reports when they test functionality.

I think to fix this we'll have to:

 * Modify deployment scripts to notify tutor-server of the current environment
 * tutor-server will pass the environment onto the FE
 * FE will substitute the environment onto it's urls

**Comment by nathanstitt** [comment]
Awaiting a chance to chat with @Dantemss on best approach

**Comment by carlycurran** [comment]
per Nathan , we already have code to do this
