### ISSUE TITLE
Make sure practice widget not assigning the same problems over and over

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#220]
See discussion at:

https://github.com/openstax/tutor-server/pull/153/files#r29286749

**Comment by Dantemss** [comment]
The current code will avoid this as long as there are at least 5 exercises for each LO.
It will repeat exercises if there are 4 exercises or less...

**Comment by Dantemss** [comment]
Code now errors out if there are less than 5 exercises. See https://github.com/openstax/tutor-server/pull/525
