### ISSUE TITLE
Remove orphaned migrations

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#251]
These migrations are orphaned -- remove and fix any specs.

db/migrate/20140724184800_create_administrators.rb
db/migrate/20140923195826_create_courses.rb
db/migrate/20140923195940_create_sections.rb
db/migrate/20140923200039_create_educators.rb

**Comment by karenc** [comment]
@jpslav I'm removing couses, section, educators and **students** (not administrators).  Are you sure we want to remove administrators?

**Comment by jpslav** [comment]
There's a `UserProfile::Models::Administrator` that I believe is the one we are keeping.  I don't think there's a model to go along with `20140724184800_create_administrators.rb` but please double check me on that.

**Comment by karenc** [comment]
I don't see any other administrators table in [db/schema.rb](https://github.com/openstax/tutor-server/blob/master/db/schema.rb), removing that migration removes the `administrators` table, so I don't think we should remove it.

**Comment by karenc** [comment]
Should we rename the `administrators` table to `user_profile_administrators`?

**Comment by karenc** [comment]
Ok renamed `administrators` to `user_profile_administrators` in #253
