### ISSUE TITLE
Background job assignment creation

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-server#302]
Unicorns making assignments are being killed in tutor-demo because they are taking longer than 30 seconds. Move assignment creation to a background job.

**Comment by jpslav** [comment]
Until we get background jobs for this, can we extend the unicorn kill time @cnuber?

**Comment by Dantemss** [comment]
When this is implemented, we need some indication of whether or not an assignment has been successfully published in the FE...

**Comment by Dantemss** [comment]
I suggest using `resque-lock-timeout` plugin to prevent a TaskPlan from being published by 2 jobs at the same time and for adding a timeout in case the worker crashes. `resque-retry` would be handy for retrying those failed jobs.

**Comment by Dantemss** [comment]
Done here: https://github.com/openstax/tutor-server/pull/392
