### ISSUE TITLE
Tutor home page has layout issues on squished resolutions

### ISSUE THREAD

**Issue by lakshmivyas** [openstax/tutor-server#311]
I have a monitor with a vertical profile.  The text blurb in the green area gets hidden behind the video.

![tutor-web-squished](https://cloud.githubusercontent.com/assets/45002/7797867/c7353520-030f-11e5-98df-16e4629d7180.png)

**Comment by jpslav** [comment]
@fredasaurus I leave all things home page in your hands :-)

**Comment by Fredasaurus** [comment]
Cool, will do.

**Comment by nathanstitt** [comment]
I poked at it a bit the other day and noticed that it uses Bootstrap.  An easy win would be to shift the video down under the "a Personalized Learning" message for smaller screen sizes.  Also shouldn't the "a" be capitalized ?   I'll volunteer for a quick PR if that sounds like a good start.

**Comment by Fredasaurus** [comment]
Yeah, I want to make sure we get the breakpoint right though. It should have to drop at that size.

Go ahead though, thanks.

**Comment by Fredasaurus** [comment]
Yeah, I want to make sure we get the breakpoint right though. It should not have to drop at that size.

Go ahead though, thanks.

**Comment by Fredasaurus** [comment]
Also, Can you do these as well?
1. Replace Nunito with Lato (that's sounds funny),
2. Update the sign in button with btn-large, btn-primary styles. 

Thanks.

**Comment by Fredasaurus** [comment]
Oh, and another thing (anyone remember Columbo?)

Can you make the logo the same size as in the app?

Thanks again.

**Comment by jpslav** [comment]
FWIW, we do somehow use Avenir font for sites like OSC (via Adobe I think).  That is the classic OpenStax font.

**Comment by Fredasaurus** [comment]
Yeah, Avenir would be my preference. Not available from Adobe Typekit. It's hosted from fonts.com.
Their pricing model is hard to decipher though. What constitutes a page view? Once this thing scales it would be hard to project a figure. http://www.fonts.com/web-fonts/plans-and-pricing

Also, Phil is philosophically opposed to paying for any font.

If these is a way to work around these issues though, I'm for it.

**Comment by Dantemss** [comment]
Solved, according to Nathan's PR
