### ISSUE TITLE
Add better logging for external communications

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-server#370]
In particular, we should log the requests sent out to Exercise/Exchange/BigLearn, because they are hard to figure out otherwise.

**Comment by jpslav** [comment]
@Dantemss do we do enough of this now? (this is an old ticket).  If not, @joemsak can you take this?

**Comment by Dantemss** [comment]
JP is making the exceptions clearer which is what I think I wanted in the first place.

**Comment by Dantemss** [comment]
Done in https://github.com/openstax/tutor-server/pull/656
