### ISSUE TITLE
Prepend redis namespaces with "tutor_"?

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#376]
Redis namespaces are global in our deployments right?  (e.g. Exercises and Tutor share the same redis server and therefore their namespaces can collide).  If this is the case, then I think the default (and deployment configured) namespaces need to be prepended with "tutor_" and the like?

e.g. these dev settings:
https://github.com/openstax/tutor-server/blob/master/config/secrets.yml.example#L20-L21

also in the other environments and I imagine each repository.

cc @cnuber @Dantemss

**Comment by lakshmivyas** [comment]
@jpslav , @cnuber , @Dantemss :  This is already taken care of on the deployment side:
https://github.com/openstax/tutor-deployment/blob/refactor/configurable-instances/templates/tutor/www/config/secrets.yml.j2#L10-L12

**Comment by jpslav** [comment]
Yay.  Still need to address on non-deployment side for when we run multiple sites in dev mode.

**Comment by Dantemss** [comment]
Only if we remove the `fake_redis` gem from dev (but then everyone has to install redis)

**Comment by jpslav** [comment]
ah `fake_redis` probably explains why timecop setting in demo script never did work for me :-(

**Comment by Dantemss** [comment]
true, but it worked in production right?

**Comment by Dantemss** [comment]
We should keep this in the back of our minds, but it's not necessary unless we decide to use real Redis in local dev.
