### ISSUE TITLE
add first_name and last_name fields to perf report

### ISSUE THREAD

**Issue by darrenmason** [openstax/tutor-server#378]
Currently student name endpoint returns combined field for student name.  firstname and lastname fields would allow sorting by lastname in report table.

**Comment by jpslav** [comment]
@karenc this should be a pretty small change and should have a good impact (teachers will expect this to be able to sort by name, etc).  Can you make this change in the API (for now just add first_name and last_name, don't remove the full name so we don't break FE).  Also, while you're at it, do this split in the performance report export too.

**Comment by philschatz** [comment]
Adding @darrenmason, @nathanstitt, and @pandafulmanda  so the following are updated as well:

- Perf Report
- Roster
- HW Review page (both class-aggregate Free responses and the "Viewing As..." in the bottom-right corner)

**Comment by jpslav** [comment]
Thanks @philschatz

**Comment by jpslav** [comment]
@philschatz @pandafulmanda @nathanstitt this should be addressed now I think with the exception of the "HW Review page" bullet above -- if that is the detailed task plan stats that has a collection of strings called `names`, please let us know how you want that API to change.
