### ISSUE TITLE
I CAN HAZ CONSISTENT /api/user/courses and /api/courses/1???

### ISSUE THREAD

**Issue by philschatz** [openstax/tutor-server#403]
`/api/user/courses` yields all the roles but not the periods and `/api/courses/1` yields all the periods but not the roles.

Can either both contain both information or have one that contains both information?

FE always calls `/api/user/courses` because it needs to know whether to display the course listing but does not "technically" need the period info).

cc @pandafulmanda, @nathanstitt

**Comment by jpslav** [comment]
Yep.

**Comment by jpslav** [comment]
@joemsak can you look into this?

https://github.com/openstax/tutor-server/blob/master/app/controllers/api/v1/courses_controller.rb#L20 seems to imply that `/api/user/courses` has both roles and periods, but that's not what @philschatz is seeing.  

Can you make sure that both routes are showing periods and roles?  

Can you also make sure that the get of `/api/courses/1` is only accessible to people who are admins or who have a role in the course?
