### ISSUE TITLE
Publishing a iReading/HW with no sections/Exercises should error early

### ISSUE THREAD

**Issue by philschatz** [openstax/tutor-server#404]
According to the @Dantemss it is possible to publish an iReading/HW without selecting any sections or exercises. I think Jason would "like" to be able to "Save as Draft" but not "Publish".

I think allowing save-empty-as-draft is a nice-to-have but it seems like publishing empty stuff should maybe be an error.

**Comment by jpslav** [comment]
Seems reasonable to me.

**Comment by Dantemss** [comment]
This is actually kind of complex because we validate the assistant-specific settings when the plan is saved (too early). After that the settings are not read again until the background job (too late).

**Comment by Dantemss** [comment]
Same as #538

**Comment by Dantemss** [comment]
Closing because it's a duplicate.
