### ISSUE TITLE
Wrap Lev::Status in Job model, add representer

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#406]
This work depends on #392's updates to the `JobController`....

Right now, if the FE requests status on a job that is no longer in redis (say it expired or was otherwise removed), we'll get a nil error in:

https://github.com/openstax/tutor-server/blob/master/app/controllers/api/v1/jobs_controller.rb#L5-L6

Ideally we'd be able to report an "unknown" state if the UUID isn't present in redis.  We'd also like to hide away the `Lev::Status` stuff.

Add a `app/models/job.rb` model that hides `Lev::Status` and is able to report information for unknown jobs, e.g.

```ruby
class Job
  def self.find(uuid)
    Job.new(uuid)
  end

  def state
    @status.nil? ? "unknown" : @status['state']
  end

  def http_status_code
    # code that is in the controller now, might even just return 
    # :ok and :accepted instead of 200 and 202
  end

  # ... more methods to expose standard properties of Lev::Status

  # ... maybe using method_missing and respond_to? to pass on other routine-specified 
  # fields (some way to pass them on anyway)

  protected

  def initialize(uuid)
    # freak out if uuid nil
    @status = Lev::Status.find(uuid)
  end
end
```

Add a `Api::V1::JobRepresenter` to spit out JSON for the `Job`.  Adding a representer will give us our standard way to document what information can be found in a job.  

The representer will need a way to add properties for the routine-specified fields.  Probably makes sense to add a `data` property in the representer that wraps all of the routine-specific fields:

```ruby
property :data,
         ...
         getter: ->(*) { 
           # `self` is the `Job` instance
           self.job_specific_fields.each do
             # some iteration to slice out the job-specific fields
             # into this `data` json
           end
         }
```

The representer should always report the `uuid` and other standard fields (like the progress, etc).

Modify the `JobController` to just get the `Job` object and represent with the new representer, remembering to still report the correct `status`

**Comment by joemsak** [comment]
Closed by #535
