### ISSUE TITLE
Redis configuration must be passed onto resque

### ISSUE THREAD

**Issue by lakshmivyas** [openstax/tutor-server#432]
On most environments, we use shared redis.   Redis connection information is available in the rails configuration file.  This should be passed onto resque using the second method outlined in: https://github.com/resque/resque#configuration.

We should also test to make sure that both the producer and the consumer use this configuration.

**Comment by Dantemss** [comment]
This has been done in https://github.com/openstax/tutor-server/blob/master/config/initializers/resque.rb
