### ISSUE TITLE
CourseGuide switching from Fake to Real client on reload after making changes

### ISSUE THREAD

**Issue by joemsak** [openstax/tutor-server#437]
Run the demo scripts

Log in as teacher
Go to http://localhost:3001/api/courses/2/teacher_guide

or Log in as student
Go to http://localhost:3001/api/courses/2/guide

Make a change in a file, like add a blank line to a representer
Reload page
See error in BigLearn::RealClient

When it loads the API before making a change, it's using the FakeClient. You can test by adding binding.pry's to the relevant code areas.

**Comment by Dantemss** [comment]
Same as https://github.com/openstax/tutor-server/issues/494

**Comment by joemsak** [comment]
Closing for dupe
