### ISSUE TITLE
Potential improvements to demo script YAML 

### ISSUE THREAD

**Issue by kevinburleigh75** [openstax/tutor-server#463]
* `periods` should not be referenced by indices because it is super error-prone
 * see [this example](https://github.com/openstax/tutor-server/blob/master/lib/tasks/demo/biology.yml#L24)
 * instead, use a handle (much like how `students` are...uh...handled)
    * handles could be defined [here](https://github.com/openstax/tutor-server/blob/master/lib/tasks/demo/biology.yml#L7)
    * recycling `name` for this purpose would probably not be a great solution

* separate completion from assignment
 * not sure if this necessarily implies separation in the YAML structure, but it might

* we should consider whether or not the same `student` role could be in multiple periods, and whether we want the demo script to support that now or not

* if we add a `latest content` flag to the command line, we'll almost certainly need to add a `no task auto-completion` flag to prevent the auto-completion safeguard from interfering with assignment distribution

**Comment by jpslav** [comment]
cc @nathanstitt @Dantemss as a heads up, not that this needs to be done now, but the next time someone is updating the demo code this is a good writeup to reference

**Comment by nathanstitt** [comment]
+1, good points.   I also think we should add a method to specify the configuration on the command line, either as a Rake argument or an ENV var.

**Comment by Dantemss** [comment]
- Agree
- Not totally sure what this means
- I think we decided not to worry about this for now
- Agree

**Comment by kevinburleigh75** [comment]
clarification on the second point:

Assignment auto-completion can cause the demo script to abort before all content has been imported.  Usually this failure is due to a mismatch in the number of task steps, and not due to content.

By separating the import and auto-completion phases, script users can still create their own assignments from the imported content.

(This issue should be lessened now that the demo script uses fixed content versions, and - presumably - whoever updates those versions will actually fix any issues before committing it.)

**Comment by Dantemss** [comment]
I agree with separating assignment creation/completion into their own rake tasks (that are still all run together by `rake demo`).

**Comment by kevinburleigh75** [comment]
The @Dantemss has a legit point.  Definitely worth considering.

**Comment by Dantemss** [comment]
Done by Nathan in https://github.com/openstax/tutor-server/pull/496
