### ISSUE TITLE
no external content for api/plans/:planId/review page

### ISSUE THREAD

**Issue by pandafulmanda** [openstax/tutor-server#472]
unlike how ```api/plans/:planId/review``` has the plan or step content in ```current_pages``` and ```spaced_pages```, the content is absent for external plan types

@jpslav

**Comment by jpslav** [comment]
There shouldn't be any content in those fields (there is no underlying data for them).

As far as I know, there are not supposed to be quick look analytics for external assignments, and likely no detailed review page either.  @philschatz -- is that right?

**Comment by pandafulmanda** [comment]
I wanted to discuss with Jason as well, but we had a discussion about the Stats review page.

![screen shot 2015-07-16 at 1 13 19 pm](https://cloud.githubusercontent.com/assets/2483873/8731360/8d04d7c2-2bbc-11e5-8b70-eda329ad0df6.png)

**Comment by jpslav** [comment]
There's not going to be much to display on the left other than "here's the URL" and these kids clicked it -- the kids who clicked it is already on the performance report (or will be)

**Comment by pandafulmanda** [comment]
k, done
