### ISSUE TITLE
Parse / render dates respecting course time zone

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#474]
Right now the `TaskingPlanRepresenter` is talking about time zones when setting `opens_at` and `due_at` (with calls to `in_time_zone`) but this doesn't appear to be respecting the course time zone (on my dev box it was just using UTC). 

Also the getter doesn't seem to be doing any time zone stuff at all -- should it be?

cc @philschatz @kevinburleigh75

**Comment by Dantemss** [comment]
The controller sets the timezone to the course's timezone in a block around the representer, so as long as the course timezone is set, it should be working...
