### ISSUE TITLE
Make CNX archive a URL in secrets

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#480]
Currently the default CNX archive URL is hardcoded in `OpenStax::Cnx::V1#set_archive_url`.  Instead, get it from secrets like we do for all of the other 3rd party sites.

Make an `openstax_cnx.rb` initializer to pull out the URL from secrets and set it in the method above.  There's still an override in `environments/test.rb` which is fine.

Coordinate with @cnuber @lakshmivyas to get the secret into deployment setup as needed.

**Comment by Dantemss** [comment]
Do we still want this?

**Comment by Dantemss** [comment]
Done in #531
