### ISSUE TITLE
Should role has_one [students, teachers] instead of has_many?

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#483]
Currently, `Entity::Role` `has_many :students` and `has_many :teachers`.  

Whenever we add a teacher or student to a class, we make new roles (`AddUserAsCourseTeacher`, `AddUserAsPeriodStudent`).  And whenever we use the role relations `students` and `teachers` we end up [just taking the first result](https://github.com/openstax/tutor-server/blob/master/app/routines/calculate_task_plan_stats.rb#L121).

So it seems like these should both be `has_one` relations.  @openstax/tutor-be-dev, do y'all agree?

**Comment by jpslav** [comment]
The above also implies that [the uniqueness constraint on roles in `Student`] (https://github.com/openstax/tutor-server/blob/master/app/subsystems/course_membership/models/student.rb#L8) should become global.

**Comment by Dantemss** [comment]
Already done on master and in #505.
