### ISSUE TITLE
use non-hash filename in local dev perf report downloads

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#492]
https://github.com/openstax/tutor-server/blob/master/app/uploaders/export_uploader.rb#L35 probably works on S3, but in the dev environment the downloaded file has a hash for a filename.  Would be nice to have the same filename as in production.

low-priority

**Comment by Dantemss** [comment]
Oh I did this some time ago. The ExportUploader doesn't use the hash if `Rails.env.development?`
