### ISSUE TITLE
Add a jobs index API for users / job listing page for admins

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#523]
/api/jobs --> returns all jobs, only for admin user

/admin/jobs --> screen that shows admin job status (nothing fancy, just a list that would need to be manually refreshed)

**Comment by jpslav** [comment]
cc @philschatz

**Comment by philschatz** [comment]
Yep, would be nice! By polling each job (or the list) we can list all the jobs, when they started and when they completed/failed ; )

**Comment by lakshmivyas** [comment]
@jpslav - why not something like: https://github.com/resque/resque-web - in the same vein as biglearn flower server?

**Comment by joemsak** [comment]
@lakshmivyas I can't remember if I tried to add that yet, and if there was a reason we declined to use it..

**Comment by lakshmivyas** [comment]
@joemsak -  Please let me know if you see any chat logs or emails about this.   If we can use this, we can run it on the same server as biglearnflower and call it something like `taskman.openstax.org`.    Will also save us from having to write and maintain this.

**Comment by joemsak** [comment]
One downside to this option is we chose ActiveJob to be able to change our queuing backend... so we'd have to change this too if that happens, or we could make a small UI that won't need to change with the underlying queuing framework. I'm currently trying to implement resque-web in our admin UI right now, however.

**Comment by jpslav** [comment]
Small UI is fine.  Like a 5-minute table of jobs, statuses.
