### ISSUE TITLE
When distributing tasks, error out if any tasks have no steps

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#538]
Occasionally, for a variety of reasons (including lack of content, BE bugs, etc), a Task in Tutor can end up with no steps.  This is understandably confusing to students.  

Add a check [right after this line in DistributeTasks](https://github.com/openstax/tutor-server/blob/6caf77e9a10d5837c064f953206c45ea5300385f/app/routines/distribute_tasks.rb#L36) to check if any tasks has 0 steps.  If so add a fatal error:

```ruby
fatal_error(code: :empty_tasks, message: 'Tasks could not be published because some tasks were empty')
```

This will send the error information to Lev's status, which the FE can check under the TaskPlan's publish job -- the status will be "failed" and the `errors` field will be populated.  FE can use the error code to make their own error message if they choose.

cc @philschatz @jason-holmes

**Comment by Dantemss** [comment]
Same as #404
