### ISSUE TITLE
Performance Book Export cell style/commenting logic is wonky

### ISSUE THREAD

**Issue by joemsak** [openstax/tutor-server#570]
In the XLSX export of performance book, the code that creates the styles array, and the code that comments cells with lateness, has a design flaw.

First off, it is dependent on manually entering the left-hand offset based on the name columns. So if column organization changes again, the yellow background style, and cell commenting logic needs to be updated to account for this. Instead it should programmatically find the first column of homework.

Second, there's a limit on the right side because the comment method can only go as far as column Z

Fix this, please

**Comment by jpslav** [comment]
Something like:

```ruby
column = 27
row = 4
"#{([''] + ('A'..'Z').to_a)[column/26]}#{('A'..'Z').to_a[column%26]}#{row}"
 => "AB4"
```
