### ISSUE TITLE
Store chapter # and section # when importing CNX book

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#59]
The front end will need to know chapter and section numbers, e.g. Chapter 4, Section 4.2, etc.

This information isn't included in the CNX data explicitly, we just need to keep count as we import the book (using 0-based indexing, which is a little odd for a book, but there's a reason for it).

Need to add a "number" string field (or some other name) to `Book` and `Page`.  Each new level of nesting will add another ".".  E.g. in College Physics that has only chapters and sections, the numbers will be "X" for chapters and "X.Y" for sections (each module / Page is a section).  For Bio, there are units above chapters, so sections would be "X.Y.Z" (three levels down).

For now, don't worry about representing this in an API, just store the value.  Talk to @Dantemss about where to look.  @philschatz can later fill us in about how to deal with "X.0" chapter introduction "sections.

**Comment by Dantemss** [comment]
`number` is already used for sort order. Need a new name.
I'm fine with storing this explicitly, since doing recursion to figure it out from the parent chapter/unit seems unnecessary and somewhat expensive.

**Comment by Dantemss** [comment]
When building the book, you can probably figure this out as "#{string_from_parent}.#{number-1}"
But number might be nil until you validate the model.

**Comment by Dantemss** [comment]
Actually... since this is not in the CNX data, is this something the CNX frontend just figures out by itself? Maybe Phil should just do whatever they do?

**Comment by jpslav** [comment]
We're going to end up giving Phil search results (so he won't be seeing the full table of contents all the time).  So we'll need to store (or be able to easily retrieve the unit/chapter/section number).

**Comment by Dantemss** [comment]
This has been solved. Closing.
