### ISSUE TITLE
Remove TaskPlan's AR belongs_to :ecosystem; just store ID

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#611]
Right now TaskPlan holds the ID of a `Content::Models::Ecosystem`, but it should just store the public ID of a `Content::Ecosystem` and retrieve that object from the `Content` SS when needed.  (don't want the relationship between SS AR's).  Have it in there now as a quick pre-beta fix (for which we are *very* appreciative!)

**Comment by Dantemss** [comment]
I feel this is moot when we get proper Task subsystem wrappers. Besides, the relations are useful for preloading stuff...

**Comment by Dantemss** [comment]
I think this is OBE. Kevin's changes to the entire system will most likely take care of this.
