### ISSUE TITLE
Couldn't find template for digesting: tasks/show

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#616]
In the log we get:

`Couldn't find template for digesting: tasks/show`
`Couldn't find template for digesting: task_steps/show`

These guys we use etagging with.  

References: 
1. https://github.com/rails/rails/issues/15255
2. https://github.com/rails/rails/issues/20333

**Comment by Dantemss** [comment]
Going to close this since I have a PR for it :)

**Comment by chirag7jain** [comment]
@Dantemss can you add the url for your pull reques

**Comment by Dantemss** [comment]
@chirag7jain PR is linked above... but basically just pass `template: false` to any calls to `stale?` or similar methods if not using a Rails template
