### ISSUE TITLE
Make a better public/500.html page

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#632]
This page is shown when unicorn is down (nginx points to it).  It needs to be branded with Tutor stuff.

One option would be to use http://icelab.com.au/articles/precompiled-rails-static-404-and-500-pages/ to generate it from our existing /app/views/errors/any.html.erb file, which would be cool if it worked (would keep this page in sync with our normal look)

@karenc can you try to use the generation method?  If it doesn't work, then reassign to me and I can make a simple page.

**Comment by karenc** [comment]
I copied the rake script in https://github.com/openstax/tutor-server/commits/public-error-pages.

May be something needs to be "require"d, I get this error ```NoMethodError: undefined method `invoke_or_reboot_rake_task' for main:Object```...

**Comment by karenc** [comment]
Also it doesn't do `render`, so I've replaced `<%= render 'layouts/header' %>` etc with the content of `_header.html.erb`.
