### ISSUE TITLE
Performance report due date off by a column

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#641]
Due date starts on the wrong column... see image.

<img width="329" alt="screenshot 2015-09-02 16 48 54" src="https://cloud.githubusercontent.com/assets/1001691/9645716/03d0c342-5193-11e5-8dbb-997f6c294459.png">

**Comment by Dantemss** [comment]
Export only?

**Comment by joemsak** [comment]
PR #637 

![screen shot 2015-09-03 at 10 33 13 am](https://cloud.githubusercontent.com/assets/98936/9661142/671395da-5227-11e5-8740-9bfae010c383.png)
