### ISSUE TITLE
Performance report needs to have task columns in reverse due date order.  

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#642]
Needs to happen in UI and in spreadsheet.  

Copying @openstax/tutor-fe-dev to see if this change is just or also them.

**Comment by jpslav** [comment]
@joemsak please reorder the items in the representer -- that'll do the work for FE -- they can also use the  due date on their own if they want.

**Comment by Dantemss** [comment]
Since I was confused about this one, I'll say it again: this story is just to reverse the order of the tasks in the performance report (last due_at Task comes first).

**Comment by nathanstitt** [comment]
The report used to sort in the SQL clause in: https://github.com/openstax/tutor-server/pull/554  Not sure if the current implementation can still use that method or not?

**Comment by joemsak** [comment]
So the latest due_date is on top?

[ { due_at Nov 2015 }, { due_at Sept 2015 } ]

Or the most upcoming due_date should be on top? 

[ { due_at Sept 2015 }, { due_at Nov 2015 } ]

Just thinking about it, it seems to me the most upcoming due_date should be on the top, no?

**Comment by joemsak** [comment]
^^ @jpslav @Dantemss can either of you clarify on the question above?

**Comment by Dantemss** [comment]
Latest due_date first. Hopefully, just have to reverse the current order (it should currently be sorting earliest due_date first).

**Comment by joemsak** [comment]
merci

**Comment by Dantemss** [comment]
Also, don't do this in the SQL query directly. We sort the array later, after it's retrieved, so the SQL order is lost.

**Comment by joemsak** [comment]
Ya… planning to do it… here: https://github.com/openstax/tutor-server/blob/master/app/subsystems/tasks/get_performance_report.rb#L40
>  
>  
>  
>

**Comment by Dantemss** [comment]
I think maybe you gotta change it here: https://github.com/openstax/tutor-server/blob/master/app/subsystems/tasks/get_performance_report.rb#L25

**Comment by joemsak** [comment]
Good catch thanks Dante
