### ISSUE TITLE
Explore overriding ActiveRecord's association attachment methods

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor-server#65]
As part of the SubSystems extraction, ActiveRecord fails to auto-detect the class_name of associated models when they're specified by a belongs_to/has_many/has_one.

To work around we've like to override the creation methods above and specify the `class_name` ourselves in one spot rather than listing them on every single association.

Our current implementation uses alias_method and ActiveRecord::Base.define_singleton_method to directly inject methods onto ActiveRecord.  This could probably be extracted into a module that we can mix into the classes that need the functionality.

**Comment by Dantemss** [comment]
@nathanstitt this is done, correct?

**Comment by nathanstitt** [comment]
Yeah it is, I'd forgotten it was hanging around still.
