### ISSUE TITLE
Notify about exception causes

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#658]
Tutor has logged at least one exception where the exception wraps another lower-level exception.  For example, we've logged a [`ClientError` from here](https://github.com/openstax/exchange-ruby/blob/master/lib/openstax/exchange/exchange.rb#L34) that wraps an underlying error.  In our current implementation, we do not log the underlying error(s).  As of Ruby 2.1, there [is a way to access these "cause" exceptions](http://ruby-doc.org/core-2.2.0/Exception.html#method-i-cause).  In our log and in our exception notifier, we should output these causes, likely in some recursive manner.

**Comment by jpslav** [comment]
In the same vein, we definitely need a spec to test this behavior and the other [big chunk of code in `rescue_from_exception`](https://github.com/openstax/tutor-server/blob/master/config/initializers/controllers.rb#L24-L90)

**Comment by Dantemss** [comment]
JP wants me to do this... which I'm doing here: https://github.com/openstax/tutor-server/pull/660

**Comment by Dantemss** [comment]
Done in #660.
