### ISSUE TITLE
Dry up duplicated code in Extra Assignment and iReading Assistants

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#694]
https://github.com/openstax/tutor-server/pull/590/files#r40872330

**Comment by jpslav** [comment]
@Dantemss please weigh in if you have recommendations.

**Comment by Dantemss** [comment]
I missed this issue for the longest time, but yeah I think what Karen suggested should work.

**Comment by Dantemss** [comment]
Duplicated code has been moved to the FragmentAssistant.
