### ISSUE TITLE
A PG::NotNullViolation occurred in periods#create:

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#789]
A PG::NotNullViolation occurred in periods#create:

 ERROR:  null value in column "enrollment_code" violates not-null constraint
DETAIL:  Failing row contains (21, 4, 5th, 2015-10-21 21:16:43.421275, 2015-10-21 21:16:43.421275, null).

 app/subsystems/course_membership/create_period.rb:7:in `exec'

See email for more detail

**Comment by Dantemss** [comment]
I think this was a migration error thing, so might not be reproducible.

**Comment by Dantemss** [comment]
As in we deployed an old version of the code to QA or something, but the database had already been migrated.

**Comment by joemsak** [comment]
@Dantemss's suspicions confirmed. I checked out that commit SHA from the info in the email (Rails root : /home/osttutor/src/tutor-ab2289e) and this version of the code doesn't have anything in place to fill in `enrollment_code` whereas now `unique_token` has us covered

**Comment by joemsak** [comment]
Relevant links to code in that commit SHA

https://github.com/openstax/tutor-server/blob/ab2289e/app/subsystems/course_membership/create_period.rb

https://github.com/openstax/tutor-server/blob/ab2289e73fc050a3e37a5843c306bed0386d4a4e/app/subsystems/course_membership/models/period.rb

If the database was ahead of the code, this makes sense why it blew up
