### ISSUE TITLE
A NoMethodError occurred in jobs#show:

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#790]
A NoMethodError occurred in jobs#show:

 undefined method `is_fatal' for #<Hash:0x007f087b05ccd0>
 app/controllers/api/v1/jobs_controller.rb:32:in `show'

see exception email for more detail

**Comment by Dantemss** [comment]
Haven't seen this one for a while, so it might be old... happened when jobs used to fail (try importing a bogus roster spreadsheet to confirm).

**Comment by joemsak** [comment]
@Dantemss is it enough to try uploading a blank CSV at `/admin/courses/1/edit#roster` and confirming that it re-renders with validation errors, because that's what happens for me

**Comment by Dantemss** [comment]
I'm not entirely sure...
Try to import one of the spreadsheets in `spec/fixtures/files` but add some blank rows and columns in between the other rows/columns. If it errors out properly (instead of 500) then it's fixed I think.

**Comment by jpslav** [comment]
I got one of these exceptions on Nov 7 from the QA server...

[Tutor] (qa) jobs#show (NoMethodError) "undefined method `is_fatal' for
#<Hash:0x007f087b05ccd0>"

**Comment by jpslav** [comment]
This was fixed by https://github.com/openstax/tutor-server/pull/840
