### ISSUE TITLE
A NoMethodError occurred in background at 2015-10-09 23:27:14 UTC :

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#791]
A NoMethodError occurred in background at 2015-10-09 23:27:14 UTC :

 undefined method `reverse' for nil:NilClass
 /home/osttutor/src/tutor-f05bc17/vendor/bundle/ruby/2.2.0/gems/axlsx-2.1.0.pre/lib/axlsx.rb:82:in `name_to_indices'

See emails for more info.

**Comment by jpslav** [comment]
Also get related:

An ArgumentError occurred in background at 2015-10-20 08:37:07 UTC :

 invalid cell name
 /home/osttutor/src/tutor-ab2289e/vendor/bundle/ruby/2.2.0/gems/axlsx-2.1.0.pre/lib/axlsx.rb:80:in `name_to_indices'

**Comment by jpslav** [comment]
Dante says: "Kajal trying to export performance report after importing the same students twice and breaking the course :)"  -- wonder if we can prevent the root problem

**Comment by Dantemss** [comment]
We are moving away from importing students through spreadsheets and I haven't seen this bug in a while, so I'll close this issue.
