### ISSUE TITLE
A NoMethodError occurred in task_plans#stats:

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#792]
A NoMethodError occurred in task_plans#stats:

 undefined method `+@' for #<Array:0x007f9d24c4cb60>
 app/routines/calculate_task_plan_stats.rb:122:in `block (2 levels) in generate_period_stat_data'

See email for more info

**Comment by Dantemss** [comment]
I `think` this has been fixed, but somehow I'm missing the original email to confirm.

**Comment by joemsak** [comment]
The commit SHA `f05bc17` referenced as the root of the deployed rails app doesn't even have this code at line 122 ??

**Comment by joemsak** [comment]
From the email I see this is the 'cause'

```
<ActionView::MissingTemplate: Missing template api/v1/task_plans/stats, api/v1/api/stats, openstax/api/v1/api/stats with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:
    * "/home/osttutor/src/tutor-f05bc17/app/views"
```

**Comment by joemsak** [comment]
https://tutor-qa.openstax.org/api/plans/9/stats Works fine for me logged in as teacher01, too

**Comment by jpslav** [comment]
Karen fixed one of these back in early Aug (
https://www.pivotaltracker.com/n/projects/1156756/stories/100568336); but
there was another variant on Oct 12 (look for that email Joe)

**Comment by Dantemss** [comment]
We haven't seen this issue in a long time, so I'm going to close this. Reopen if it shows up again.
