### ISSUE TITLE
Tasks::Models::Task#late? explodes when due_at nil

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#811]
This code in `Tasks::Models::Task`...

```ruby
  def late?
    worked_on? && last_worked_at > due_at
  end
```

bombs when `due_at` is `nil`, which it is allowed to be (happens for practice widget and concept coach).  Since these tasks have no due date, they should never be late.

**Comment by Dantemss** [comment]
Hm guess nil `due_at` never happened before Concept Coach.

**Comment by jpslav** [comment]
it is nil in practice widget, but those aren't in the scores report, so we never ask about their lateness.

**Comment by Dantemss** [comment]
Taking over since we need this now.

**Comment by Dantemss** [comment]
Fixed here: https://github.com/openstax/tutor-server/pull/826
