### ISSUE TITLE
Better openuri exception reporting

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#838]
https://github.com/openstax/tutor-server/blob/master/lib/openstax/cnx/v1.rb#L57

rescue `OpenURI::HTTPError` and reraise as some sort of Tutor HTTP error, including the URL being targeted so we can figure out what URL caused the error.  Append the rescued exception's message (e.g. "404 Not Found").  Exception email fragment that we get now is pasted below.

Check to see other places we could get this `OpenURI::HTTPError`, e.g. when we get Exercises?

Spec this by fetching made up URLs.

```
An OpenURI::HTTPError occurred in background at 2015-11-30 20:33:20 UTC :

  404 Not Found
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:358:in `open_http'

  -------------------------------
Backtrace:
-------------------------------

  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:358:in `open_http'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:716:in `open'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:34:in `open'
  /home/osttutor/src/tutor-7a13459/lib/openstax/cnx/v1.rb:57:in `fetch'
```

**Comment by joemsak** [comment]
@jpslav Not sure about using it on exercises because it does not appear the caller can make a URL that will 404, it just adds to a query param on a predefined URL

**Comment by jpslav** [comment]
this error is cnx, not exercises

**Comment by joemsak** [comment]
I interpreted "Check to see other places we could get this OpenURI::HTTPError, e.g. when we get Exercises?" as the `/lib/openstax/exercises/` stuff. Am I wrong?

**Comment by jpslav** [comment]
no

**Comment by joemsak** [comment]
Okay, so in the code for the real client, the URL is predefined inside the code and the config settings. The caller can only manipulate the query which one should be able to reasonably assume at worst returns no results

**Comment by jpslav** [comment]
My last message agreed with you :-)

**Comment by joemsak** [comment]
Okay, I wasn't sure if 'no' meant I'm not wrong about exercises being in there, or if you wanted me to find something in the cnx folder related to it :)
