### ISSUE TITLE
Reading/Homework Spaced Practice Algorithm needs changes

### ISSUE THREAD

**Issue by kevinburleigh75** [openstax/tutor-server#877]
There are two simple changes that should be made ASAP:

* after excluding previously-worked exercises, the number of SPEs assigned should be `min(k-ago map value, remaining exercises)`
* even if one k-ago slot cannot be satisfied (because we ran out of exercises), we should continue on to the next slot

Changing [this](https://github.com/openstax/tutor-server/blob/master/app/subsystems/tasks/assistants/homework_assistant.rb#L145) and [this](https://github.com/openstax/tutor-server/blob/master/app/subsystems/tasks/assistants/i_reading_assistant.rb#L167) from 
```ruby
break if candidate_exercises.size < number
```
to
```ruby
number = [candidate_exercises.size, number].min
next if number == 0
```
should do the trick.  Perhaps a new variable should be created instead of changing `number`.

The more complicated adjustment is:
* after excluding previously-worked exercises and drawing from the remaining set, if more exercises are needed we should re-consider previously-worked exercises (though not those already chosen in for the current assignment)

Pseudocode for all of this:
```
chosen_exercises = []

if chosen_exercises.count < number
  chosen_exercises = (candidate_exercises - worked_exercises).shuffle.first(number)

if chosen_exercises.count < number
  chosen_exercises.append (candidate_exercises - chosen_exercises).shuffle.first(number-chosen_exercises.count)

next if chosen_exercises.none?

add_steps_for(chosen_exercises)
```

**Comment by jpslav** [comment]
Also, when we cannot continue filling spaced practice, we should note the reason in the Task's spy info.
