### ISSUE TITLE
Optimize bulk course updates

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-server#971]
For each set of to/from ecosystems, cache the result of whether the Ecosystem mapping is valid or not, possibly in redis, and reuse the cached result for further comparisons.

**Comment by Dantemss** [comment]
Could just put the caching logic in the Content::Strategies::Generated::Map class.

**Comment by Dantemss** [comment]
This is highly necessary IMO because Concept Coach book updates are now taking several hours.

**Comment by jpslav** [comment]
Made this a change request.
